[mypy]
exclude = tests

# Same near-strict settings as tex2pdf-service/mypy.ini
disallow_untyped_defs=True
check_untyped_defs=True
disallow_any_decorated=false
warn_redundant_casts=True
warn_return_any=True
warn_unused_ignores=True
warn_unused_configs=True
no_implicit_optional=True
strict_optional=True
disallow_untyped_calls=True
ignore_missing_imports=True
follow_imports=silent
