# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Submission Tools Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with: # install extra packages we use in the test files
        packages: |
          scheme-basic
          index
          lipsum
          amsmath
          csquotes
          biblatex
    - name: Install dependencies for tools
      run: |
        cd tex2pdf-tools
        python -m pip install --upgrade pip
        pip install pytest poetry
        poetry install
    - name: pytest for tools
      run: |
        cd tex2pdf-tools
        export PYTHONPATH=$PWD
        poetry run pytest tests
